Fix image overflowing
jhcloos/jhcloos.github.io pull request #14
Opened 2022-06-22 21:17 UTC by Illutax

2022-09-08 08:46 UTC, Cplus360 approved these changes
Okay changes updated

2022-09-10 06:26 UTC, 19john90 requested changes
e4d035adc07b4eaee3a636d6f9e440227ec1888d

2022-09-23 00:38 UTC, Bahigac approved these changes

2023-02-27 10:21 UTC, BADGIRL09 approved these changes

2023-03-15 17:26 UTC, gipnomag approved these changes

2023-06-22 08:13 UTC, influencep approved these changes

2023-06-22 08:13 UTC, influencep approved these changes

2023-07-23 22:08 UTC, Hayderhammami approved these changes

2023-09-01 06:23 UTC, NTDLS commented
This is still overflowing on my iPhone SE.

2024-06-28 09:28 UTC, blacksmithop requested changes
Needs review

2024-07-06 13:44 UTC, Findrown approved these changes

2024-09-29 16:05 UTC, EricMujjona requested changes
# changes

2024-10-11 20:26 UTC, Fataah99 approved these changes

2024-12-02 01:56 UTC, DIDIx13 approved these changes

2025-01-13 10:55 UTC, Scutua approved these changes

2025-01-15 07:19 UTC, Scutua approved these changes

2025-03-02 18:33 UTC, podpsek approved these changes

2025-08-07 22:01 UTC, closed without merging